-- PostgreSQL Initialization Script
-- Creates extensions and initial setup for DotMac Platform

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";  -- For text search
CREATE EXTENSION IF NOT EXISTS "btree_gin"; -- For GIN indexes

-- Create application schema (optional, using public by default)
-- CREATE SCHEMA IF NOT EXISTS dotmac;

-- Set default permissions
-- GRANT ALL PRIVILEGES ON SCHEMA public TO dotmac_user;

-- Performance tuning
-- --------------------------------------------------
-- Apply environment-specific tuning generated by:
--   ./scripts/generate-db-config.sh (preferred)
--   ./scripts/pgtune.sh 4096 web ssd
-- Set DOTMAC_TUNING_FILE to the generated SQL (psql -v DOTMAC_TUNING_FILE=...)
\if :{?DOTMAC_TUNING_FILE}
  \echo 'Applying tuning from :'DOTMAC_TUNING_FILE
  \ir :'DOTMAC_TUNING_FILE'
  SELECT pg_reload_conf();
\else
  \echo 'Skipping database tuning (DOTMAC_TUNING_FILE not set).'
\endif

-- NOTE: The recommended workflow is to run ./scripts/generate-db-config.sh (or
--       ./scripts/pgtune.sh <ram_mb> web ssd) and pass the resulting SQL file via
--       DOTMAC_TUNING_FILE so each environment gets the correct parameters.

-- Create read-only user for reporting (optional)
-- DO $$
-- BEGIN
--     IF NOT EXISTS (SELECT FROM pg_user WHERE usename = 'dotmac_readonly') THEN
--         CREATE USER dotmac_readonly WITH PASSWORD 'readonly_password';
--         GRANT CONNECT ON DATABASE dotmac_prod TO dotmac_readonly;
--         GRANT USAGE ON SCHEMA public TO dotmac_readonly;
--         GRANT SELECT ON ALL TABLES IN SCHEMA public TO dotmac_readonly;
--         ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO dotmac_readonly;
--     END IF;
-- END
-- $$;
