// React Query Hooks
// Centralized exports for all API hooks

// Auth hooks
export {
  useCurrentUser,
  useUpdateProfile,
  useChangePassword,
  useSessions,
  useRevokeSession,
  useSetupMfa,
  useEnableMfa,
  useDisableMfa,
} from "./use-auth";

// Users hooks
export {
  useUsers,
  useUser,
  useCreateUser,
  useUpdateUser,
  useDeleteUser,
  useSuspendUser,
  useActivateUser,
  useResendInvite,
  useResetPassword,
  type ListUsersParams,
  type CreateUserData,
  type UpdateUserData,
} from "./use-users";

// Tenants hooks
export {
  useTenants,
  useTenant,
  useCurrentTenant,
  useTenantBySlug,
  useCreateTenant,
  useUpdateTenant,
  useDeleteTenant,
  useSuspendTenant,
  useActivateTenant,
  useRestoreTenant,
  useTenantStats,
  useTenantSettings,
  useUpdateTenantSettings,
  type ListTenantsParams,
  type CreateTenantData,
  type UpdateTenantData,
  type TenantStats,
} from "./use-tenants";

// Billing hooks
export {
  useBillingMetrics,
  useInvoices,
  useInvoice,
  useCreateInvoice,
  useSendInvoice,
  useMarkInvoicePaid,
  useVoidInvoice,
  useDownloadInvoicePdf,
  useSubscriptions,
  useSubscription,
  useCancelSubscription,
  usePaymentMethods,
  useSetDefaultPaymentMethod,
  useDeletePaymentMethod,
  useProcessPayment,
  type BillingMetrics,
  type ListInvoicesParams,
  type ListSubscriptionsParams,
  type CreateInvoiceData,
  type PaymentData,
} from "./use-billing";

// Customers hooks
export {
  useCustomers,
  useCustomer,
  useCreateCustomer,
  useUpdateCustomer,
  useDeleteCustomer,
  useCustomerMetrics,
  useAddCustomerTag,
  useRemoveCustomerTag,
  useAssignCustomer,
  type ListCustomersParams,
  type CreateCustomerData,
  type UpdateCustomerData,
  type CustomerMetrics,
} from "./use-customers";

// Deployments hooks
export {
  useDeployments,
  useDeployment,
  useCreateDeployment,
  useUpdateDeployment,
  useDeleteDeployment,
  useProvisionDeployment,
  useDestroyDeployment,
  useScaleDeployment,
  useRestartDeployment,
  useUpgradeDeployment,
  useDeploymentStatus,
  useDeploymentMetrics,
  useDeploymentLogs,
  type ListDeploymentsParams,
  type CreateDeploymentData,
  type UpdateDeploymentData,
  type ScaleDeploymentData,
  type DeploymentStatusResponse,
  type DeploymentLogs,
} from "./use-deployments";

// Analytics hooks
export {
  useDashboardMetrics,
  useRevenueData,
  useActivityFeed,
  useSystemHealth,
  useTrafficData,
  useGeographicData,
  useAnalyticsMetrics,
  type DashboardMetrics,
  type RevenueDataPoint,
  type ActivityItem,
  type SystemHealth,
  type SystemHealthService,
  type TrafficData,
  type GeographicData,
} from "./use-analytics";

// ============================================================================
// New Hook Modules
// ============================================================================

// Consolidated Dashboard hooks
export {
  useSecurityMetrics,
  useOperationsMetrics,
  useBillingDashboard,
  useInfrastructureHealth,
  useMonitoringMetrics,
  useLogStats,
  type SecurityMetrics,
  type OperationsMetrics,
  type BillingDashboardMetrics,
  type InfrastructureHealth,
  type MonitoringMetrics,
  type LogStats,
} from "./use-consolidated";

// Monitoring hooks
export {
  useLogs,
  useLogEntry,
  useLogStats as useMonitoringLogStats,
  useLogServices,
  useSearchLogs,
  useExportLogs,
  type GetLogsParams,
  type LogEntry,
  type LogStats as MonitoringLogStats,
  type LogSearchQuery,
} from "./use-monitoring";

// Alerts hooks
export {
  useAlertChannels,
  useAlertChannel,
  useCreateAlertChannel,
  useUpdateAlertChannel,
  useDeleteAlertChannel,
  useTestAlertChannel,
  useEnableAlertChannel,
  useDisableAlertChannel,
  useAlertRules,
  useAlertRule,
  useCreateAlertRule,
  useUpdateAlertRule,
  useDeleteAlertRule,
  useEnableAlertRule,
  useDisableAlertRule,
  useAlertHistory,
  useAcknowledgeAlert,
  useResolveAlert,
  useAlertStats,
  type AlertChannel,
  type CreateAlertChannelData,
  type AlertTestResult,
  type AlertRule,
  type CreateAlertRuleData,
  type AlertHistoryParams,
  type AlertEvent,
  type AlertStats,
} from "./use-alerts";

// Observability hooks
export {
  useTraces,
  useTrace,
  useTraceSpans,
  useMetrics,
  useMetricsSeries,
  useQueryMetrics,
  useServiceMap,
  useServiceDependencies,
  usePerformanceAnalytics,
  useEndpointPerformance,
  useSlowEndpoints,
  type GetTracesParams,
  type TraceData,
  type TraceSpan,
  type MetricsQueryParams,
  type MetricSeries,
  type ServiceMap,
  type ServiceDependency,
  type PerformanceAnalytics,
  type EndpointPerformance,
} from "./use-observability";

// Ticketing hooks
export {
  useTickets,
  useTicket,
  useCreateTicket,
  useUpdateTicket,
  useDeleteTicket,
  useTicketMessages,
  useAddTicketMessage,
  useAssignTicket,
  useAutoAssignTicket,
  useUpdateTicketStatus,
  useAddTicketTags,
  useRemoveTicketTag,
  useLinkTickets,
  useTicketStats,
  useAgentPerformance,
  type GetTicketsParams,
  type Ticket,
  type TicketMessage,
  type CreateTicketData,
  type TicketStats,
  type AgentPerformance,
} from "./use-ticketing";

// Workflows hooks
export {
  useWorkflows,
  useWorkflow,
  useCreateWorkflow,
  useUpdateWorkflow,
  useDeleteWorkflow,
  usePublishWorkflow,
  useUnpublishWorkflow,
  useCloneWorkflow,
  useWorkflowVersions,
  useWorkflowVersion,
  useWorkflowExecutions,
  useWorkflowExecution,
  useExecuteWorkflow,
  useCancelExecution,
  useRetryExecution,
  useExecutionLogs,
  useWorkflowStats,
  type GetWorkflowsParams,
  type Workflow,
  type WorkflowVersion,
  type WorkflowExecution,
  type ExecutionLog,
  type WorkflowStats,
  type CreateWorkflowData,
} from "./use-workflows";

// Jobs hooks
export {
  useJobs,
  useJob,
  useCreateJob,
  useCancelJob,
  useRetryJob,
  useJobProgress,
  useJobLogs,
  useScheduledJobs,
  useScheduledJob,
  useCreateScheduledJob,
  useUpdateScheduledJob,
  useDeleteScheduledJob,
  usePauseScheduledJob,
  useResumeScheduledJob,
  useTriggerScheduledJob,
  useJobStats,
  useJobQueues,
  usePurgeQueue,
  type GetJobsParams,
  type Job,
  type JobProgress,
  type JobLog,
  type ScheduledJob,
  type CreateJobData,
  type CreateScheduledJobData,
  type JobStats,
  type JobQueue,
} from "./use-jobs";

// Communications hooks
export {
  useSendEmail,
  useSendBulkEmails,
  useEmailTemplates,
  useEmailTemplate,
  useCreateEmailTemplate,
  useUpdateEmailTemplate,
  useDeleteEmailTemplate,
  usePreviewEmailTemplate,
  useTestEmailTemplate,
  useQueueBulkEmail,
  useBulkEmailJob,
  useCancelBulkEmailJob,
  useEmailLogs,
  useEmailLog,
  useResendEmail,
  useCommunicationStats,
  type EmailRequest,
  type EmailResponse,
  type GetTemplatesParams,
  type EmailTemplate,
  type CreateEmailTemplateData,
  type BulkEmailJob,
  type GetEmailLogsParams,
  type EmailLog,
  type CommunicationStats,
} from "./use-communications";

// Partners hooks
export {
  usePartners,
  usePartner,
  useCreatePartner,
  useUpdatePartner,
  useDeletePartner,
  useActivatePartner,
  useDeactivatePartner,
  usePartnerUsers,
  useAddPartnerUser,
  useRemovePartnerUser,
  usePartnerAccounts,
  useAddPartnerAccount,
  useRemovePartnerAccount,
  usePartnerCommissions,
  useCreateCommissionEvent,
  useProcessCommissionPayout,
  usePartnerPayouts,
  useReferrals,
  useCreateReferral,
  useConvertReferral,
  usePartnerDashboard,
  usePartnerStats,
  type GetPartnersParams,
  type Partner,
  type CreatePartnerData,
  type PartnerUser,
  type PartnerAccount,
  type CommissionEvent,
  type PartnerPayout,
  type ReferralLead,
  type PartnerDashboard,
  type PartnerStats,
} from "./use-partners";

// Contacts hooks
export {
  useContacts,
  useContact,
  useCreateContact,
  useUpdateContact,
  useDeleteContact,
  useSearchContacts,
  useContactMethods,
  useAddContactMethod,
  useUpdateContactMethod,
  useDeleteContactMethod,
  useSetPrimaryContactMethod,
  useContactActivities,
  useAddContactActivity,
  useContactTags,
  useAddContactTag,
  useRemoveContactTag,
  useMergeContacts,
  useBulkUpdateContacts,
  useBulkDeleteContacts,
  useImportContacts,
  useExportContacts,
  useContactStats,
  type GetContactsParams,
  type Contact,
  type CreateContactData,
  type ContactSearchQuery,
  type ContactMethod,
  type ContactActivity,
  type ContactStats,
} from "./use-contacts";

// Notifications hooks
export {
  useNotifications,
  useNotification,
  useMarkNotificationAsRead,
  useMarkAllNotificationsAsRead,
  useDeleteNotification,
  useUnreadNotificationsCount,
  useNotificationPreferences,
  useUpdateNotificationPreferences,
  useSendTeamNotification,
  type GetNotificationsParams,
  type Notification,
  type NotificationPreferences,
} from "./use-notifications";

// Webhooks hooks
export {
  useWebhooks,
  useWebhook,
  useCreateWebhook,
  useUpdateWebhook,
  useDeleteWebhook,
  useEnableWebhook,
  useDisableWebhook,
  useTestWebhook,
  useRotateWebhookSecret,
  useWebhookDeliveries,
  useWebhookDelivery,
  useRetryWebhookDelivery,
  useWebhookEvents,
  useWebhookStats,
  type WebhookSubscription,
  type CreateWebhookData,
  type WebhookTestResult,
  type GetDeliveriesParams,
  type WebhookDelivery,
  type WebhookEventInfo,
  type WebhookStats,
} from "./use-webhooks";

// Integrations hooks
export {
  useIntegrations,
  useIntegration,
  useCreateIntegration,
  useUpdateIntegration,
  useDeleteIntegration,
  useEnableIntegration,
  useDisableIntegration,
  useTestIntegration,
  useSyncIntegration,
  useIntegrationLogs,
  useAvailableIntegrations,
  type Integration,
  type CreateIntegrationData,
  type IntegrationLog,
  type AvailableIntegration,
} from "./use-integrations";

// Secrets hooks
export {
  useSecrets,
  useSecret,
  useSecretMetadata,
  useCreateSecret,
  useUpdateSecret,
  useDeleteSecret,
  useUndeleteSecret,
  useDestroySecret,
  useSecretsHealth,
  useSecretsMetrics,
  useRotateSecret,
  useRotationPolicies,
  useSetRotationPolicy,
  type Secret,
  type SecretValue,
  type SecretMetadata,
  type SecretsMetrics,
  type RotationPolicy,
} from "./use-secrets";

// Feature Flags hooks
export {
  useFeatureFlags,
  useFeatureFlag,
  useCreateFeatureFlag,
  useUpdateFeatureFlag,
  useDeleteFeatureFlag,
  useEnableFeatureFlag,
  useDisableFeatureFlag,
  useCheckFeatureFlag,
  useCheckFeatureFlags,
  useFeatureFlagStatus,
  useClearFeatureFlagCache,
  useSyncFeatureFlagsToRedis,
  type FeatureFlag,
  type CreateFeatureFlagData,
  type FeatureFlagCheck,
  type FeatureFlagStatus,
} from "./use-feature-flags";

// Licensing hooks
export {
  useLicenses,
  useLicense,
  useLicenseByKey,
  useCreateLicense,
  useUpdateLicense,
  useDeleteLicense,
  useValidateLicense,
  useValidateActivation,
  useLicenseActivations,
  useCreateActivation,
  useDeactivateActivation,
  useSendHeartbeat,
  useRenewLicense,
  useTransferLicense,
  useSuspendLicense,
  useReactivateLicense,
  useLicenseTemplates,
  useCreateLicenseFromTemplate,
  useGenerateEmergencyCode,
  useValidateEmergencyCode,
  type GetLicensesParams,
  type License,
  type CreateLicenseData,
  type LicenseValidationResult,
  type LicenseActivation,
  type LicenseTemplate,
} from "./use-licensing";

// Audit hooks
export {
  useAuditActivities,
  useAuditActivity,
  useSearchAuditActivities,
  useAuditStats,
  useExportAuditActivities,
  useLogFrontendError,
  useLogFrontendErrors,
  useUserActivitySummary,
  type GetAuditParams,
  type AuditActivity,
  type AuditSearchQuery,
  type AuditStats,
  type FrontendLogEntry,
  type UserActivitySummary,
} from "./use-audit";

// Plugins hooks
export {
  usePlugins,
  usePlugin,
  usePluginSchema,
  useAvailablePlugins,
  useRefreshPlugins,
  useEnablePlugin,
  useDisablePlugin,
  useUpdatePlugin,
  usePluginInstances,
  usePluginInstance,
  useCreatePluginInstance,
  useUpdatePluginInstance,
  useDeletePluginInstance,
  usePluginInstanceConfiguration,
  useUpdatePluginInstanceConfiguration,
  useTestPlugin,
  useTestPluginInstance,
  usePluginInstanceHealth,
  useCheckAllInstancesHealth,
  usePluginCategories,
  usePluginsByCategory,
  type Plugin,
  type PluginConfigSchema,
  type PluginInstance,
  type PluginTestResult,
  type PluginStatus,
} from "./use-plugins";

// Partner Portal hooks (self-service)
export {
  usePartnerDashboard as usePartnerPortalDashboard,
  usePartnerReferrals as usePartnerPortalReferrals,
  useReferral,
  useCreateReferral as useCreatePortalReferral,
  useUpdateReferral,
  usePartnerCustomers as usePartnerPortalCustomers,
  usePartnerCommissions as usePartnerPortalCommissions,
  usePartnerStatements,
  useStatement,
  useDownloadStatement,
  usePartnerPayouts as usePartnerPortalPayouts,
  usePartnerProfile,
  useUpdatePartnerProfile,
} from "./use-partner-portal";

// Tenant Portal hooks (self-service)
export {
  useTenantDashboard as useTenantPortalDashboard,
  useTenantMembers,
  useTenantMember,
  useUpdateMemberRole,
  useRemoveMember,
  useTenantInvitations,
  useInviteMember,
  useCancelInvitation,
  useResendInvitation,
  useTenantBilling,
  useTenantInvoices,
  useDownloadInvoice,
  useTenantUsage,
  useTenantUsageBreakdown,
  useTenantSettings as useTenantPortalSettings,
  useUpdateTenantSettings as useUpdateTenantPortalSettings,
  useApiKeys,
  useCreateApiKey,
  useDeleteApiKey,
} from "./use-tenant-portal";
