/**
 * Migration Map for MUI to DotMac Primitives
 *
 * This file provides mappings for converting Material-UI components
 * to DotMac Primitives components.
 */

export const componentMigrationMap = {
  // Core Components
  '@mui/material/Button': '@dotmac/primitives',
  '@mui/material/TextField': '@dotmac/primitives',
  '@mui/material/Card': '@dotmac/primitives',
  '@mui/material/CardContent': '@dotmac/primitives',
  '@mui/material/CardActions': '@dotmac/primitives',
  '@mui/material/Dialog': '@dotmac/primitives',
  '@mui/material/DialogTitle': '@dotmac/primitives',
  '@mui/material/DialogContent': '@dotmac/primitives',
  '@mui/material/DialogActions': '@dotmac/primitives',
  '@mui/material/Alert': '@dotmac/primitives',
  '@mui/material/Tabs': '@dotmac/primitives',
  '@mui/material/Tab': '@dotmac/primitives',
  '@mui/material/Box': '@dotmac/primitives',
  '@mui/material/Container': '@dotmac/primitives',
  '@mui/material/Grid': '@dotmac/primitives',
  '@mui/material/Typography': '@dotmac/primitives',
  '@mui/material/Paper': '@dotmac/primitives',
  '@mui/material/Divider': '@dotmac/primitives',
  '@mui/material/List': '@dotmac/primitives',
  '@mui/material/ListItem': '@dotmac/primitives',
  '@mui/material/ListItemText': '@dotmac/primitives',
  '@mui/material/IconButton': '@dotmac/primitives',
  '@mui/material/Checkbox': '@dotmac/primitives',
  '@mui/material/Radio': '@dotmac/primitives',
  '@mui/material/RadioGroup': '@dotmac/primitives',
  '@mui/material/Select': '@dotmac/primitives',
  '@mui/material/MenuItem': '@dotmac/primitives',
  '@mui/material/FormControl': '@dotmac/primitives',
  '@mui/material/FormLabel': '@dotmac/primitives',
  '@mui/material/FormHelperText': '@dotmac/primitives',
  '@mui/material/Switch': '@dotmac/primitives',
  '@mui/material/Slider': '@dotmac/primitives',
  '@mui/material/Tooltip': '@dotmac/primitives',
  '@mui/material/Snackbar': '@dotmac/primitives',
  '@mui/material/Avatar': '@dotmac/primitives',
  '@mui/material/Badge': '@dotmac/primitives',
  '@mui/material/Chip': '@dotmac/primitives',
  '@mui/material/CircularProgress': '@dotmac/primitives',
  '@mui/material/LinearProgress': '@dotmac/primitives',
  '@mui/material/Skeleton': '@dotmac/primitives',
  '@mui/material/Accordion': '@dotmac/primitives',
  '@mui/material/AccordionSummary': '@dotmac/primitives',
  '@mui/material/AccordionDetails': '@dotmac/primitives',
  '@mui/material/AppBar': '@dotmac/primitives',
  '@mui/material/Toolbar': '@dotmac/primitives',
  '@mui/material/Drawer': '@dotmac/primitives',
  '@mui/material/Menu': '@dotmac/primitives',
  '@mui/material/Popover': '@dotmac/primitives',
  '@mui/material/Modal': '@dotmac/primitives',
  '@mui/material/Backdrop': '@dotmac/primitives',
  '@mui/material/Table': '@dotmac/primitives',
  '@mui/material/TableBody': '@dotmac/primitives',
  '@mui/material/TableCell': '@dotmac/primitives',
  '@mui/material/TableContainer': '@dotmac/primitives',
  '@mui/material/TableHead': '@dotmac/primitives',
  '@mui/material/TableRow': '@dotmac/primitives',
  '@mui/material/TablePagination': '@dotmac/primitives',
};

// Icon mappings from MUI Icons to Lucide React
export const iconMigrationMap: Record<string, string> = {
  // Navigation
  'Menu': 'Menu',
  'MenuOpen': 'Menu',
  'Close': 'X',
  'ArrowBack': 'ArrowLeft',
  'ArrowForward': 'ArrowRight',
  'ArrowUpward': 'ArrowUp',
  'ArrowDownward': 'ArrowDown',
  'ChevronLeft': 'ChevronLeft',
  'ChevronRight': 'ChevronRight',
  'ExpandMore': 'ChevronDown',
  'ExpandLess': 'ChevronUp',
  'MoreVert': 'MoreVertical',
  'MoreHoriz': 'MoreHorizontal',

  // Actions
  'Add': 'Plus',
  'Remove': 'Minus',
  'Delete': 'Trash',
  'DeleteOutline': 'Trash2',
  'Edit': 'Edit',
  'EditOutlined': 'Edit2',
  'Save': 'Save',
  'SaveAlt': 'Download',
  'Clear': 'X',
  'Check': 'Check',
  'CheckCircle': 'CheckCircle',
  'Cancel': 'XCircle',
  'Refresh': 'RefreshCw',
  'Sync': 'RefreshCw',
  'Undo': 'Undo',
  'Redo': 'Redo',
  'ContentCopy': 'Copy',
  'ContentPaste': 'Clipboard',
  'ContentCut': 'Scissors',
  'Print': 'Printer',
  'Share': 'Share',
  'Download': 'Download',
  'Upload': 'Upload',
  'CloudUpload': 'CloudUpload',
  'CloudDownload': 'CloudDownload',

  // Communication
  'Email': 'Mail',
  'Mail': 'Mail',
  'MailOutline': 'Mail',
  'Send': 'Send',
  'Message': 'MessageSquare',
  'Chat': 'MessageCircle',
  'Forum': 'MessageSquare',
  'Phone': 'Phone',
  'Call': 'Phone',
  'Notifications': 'Bell',
  'NotificationsNone': 'Bell',
  'NotificationsActive': 'BellRing',

  // Media
  'PlayArrow': 'Play',
  'Pause': 'Pause',
  'Stop': 'Square',
  'SkipNext': 'SkipForward',
  'SkipPrevious': 'SkipBack',
  'FastForward': 'FastForward',
  'FastRewind': 'Rewind',
  'VolumeUp': 'Volume2',
  'VolumeDown': 'Volume1',
  'VolumeMute': 'VolumeX',
  'VolumeOff': 'VolumeX',
  'Mic': 'Mic',
  'MicOff': 'MicOff',
  'Videocam': 'Video',
  'VideocamOff': 'VideoOff',
  'PhotoCamera': 'Camera',
  'Image': 'Image',
  'AudioTrack': 'Music',
  'MusicNote': 'Music',

  // Files & Folders
  'Folder': 'Folder',
  'FolderOpen': 'FolderOpen',
  'CreateNewFolder': 'FolderPlus',
  'InsertDriveFile': 'File',
  'Description': 'FileText',
  'AttachFile': 'Paperclip',
  'CloudQueue': 'Cloud',
  'Cloud': 'Cloud',
  'CloudOff': 'CloudOff',

  // User & Account
  'Person': 'User',
  'PersonOutline': 'User',
  'PersonAdd': 'UserPlus',
  'PersonRemove': 'UserMinus',
  'People': 'Users',
  'Group': 'Users',
  'GroupAdd': 'UserPlus',
  'AccountCircle': 'UserCircle',
  'Face': 'Smile',
  'Lock': 'Lock',
  'LockOpen': 'Unlock',
  'LockOutlined': 'Lock',
  'VpnKey': 'Key',
  'Security': 'Shield',
  'VerifiedUser': 'ShieldCheck',

  // Common UI
  'Home': 'Home',
  'Search': 'Search',
  'Settings': 'Settings',
  'SettingsOutlined': 'Settings',
  'Build': 'Wrench',
  'Help': 'HelpCircle',
  'HelpOutline': 'HelpCircle',
  'Info': 'Info',
  'InfoOutlined': 'Info',
  'Warning': 'AlertTriangle',
  'WarningAmber': 'AlertTriangle',
  'Error': 'XCircle',
  'ErrorOutline': 'AlertCircle',
  'ReportProblem': 'AlertTriangle',
  'Flag': 'Flag',
  'Bookmark': 'Bookmark',
  'BookmarkBorder': 'Bookmark',
  'Star': 'Star',
  'StarBorder': 'Star',
  'StarHalf': 'StarHalf',
  'Favorite': 'Heart',
  'FavoriteBorder': 'Heart',
  'ThumbUp': 'ThumbsUp',
  'ThumbDown': 'ThumbsDown',
  'Comment': 'MessageSquare',

  // Business & Data
  'Work': 'Briefcase',
  'Business': 'Building',
  'Store': 'Store',
  'ShoppingCart': 'ShoppingCart',
  'ShoppingBag': 'ShoppingBag',
  'Payment': 'CreditCard',
  'CreditCard': 'CreditCard',
  'Receipt': 'Receipt',
  'Assessment': 'BarChart',
  'Analytics': 'TrendingUp',
  'TrendingUp': 'TrendingUp',
  'TrendingDown': 'TrendingDown',
  'BarChart': 'BarChart',
  'ShowChart': 'LineChart',
  'PieChart': 'PieChart',
  'Timeline': 'Activity',
  'CalendarToday': 'Calendar',
  'Event': 'Calendar',
  'Schedule': 'Clock',
  'AccessTime': 'Clock',
  'Alarm': 'AlarmClock',
  'History': 'History',

  // Location
  'Place': 'MapPin',
  'LocationOn': 'MapPin',
  'LocationOff': 'MapPinOff',
  'Map': 'Map',
  'Navigation': 'Navigation',
  'Explore': 'Compass',
  'NearMe': 'Navigation',

  // Device & System
  'Computer': 'Monitor',
  'DesktopWindows': 'Monitor',
  'Laptop': 'Laptop',
  'Smartphone': 'Smartphone',
  'Tablet': 'Tablet',
  'Keyboard': 'Keyboard',
  'Mouse': 'Mouse',
  'Memory': 'HardDrive',
  'Storage': 'Database',
  'Wifi': 'Wifi',
  'WifiOff': 'WifiOff',
  'Bluetooth': 'Bluetooth',
  'Battery': 'Battery',
  'BatteryFull': 'BatteryFull',
  'BatteryCharging': 'BatteryCharging',
  'PowerSettingsNew': 'Power',

  // Misc
  'Visibility': 'Eye',
  'VisibilityOff': 'EyeOff',
  'ZoomIn': 'ZoomIn',
  'ZoomOut': 'ZoomOut',
  'Fullscreen': 'Maximize',
  'FullscreenExit': 'Minimize',
  'OpenInNew': 'ExternalLink',
  'OpenInFull': 'Expand',
  'Launch': 'ExternalLink',
  'Link': 'Link',
  'LinkOff': 'LinkOff',
  'Code': 'Code',
  'FilterList': 'Filter',
  'Sort': 'ArrowUpDown',
  'SwapVert': 'ArrowUpDown',
  'DragHandle': 'GripVertical',
  'DragIndicator': 'GripVertical',
  'Dashboard': 'LayoutDashboard',
  'Widgets': 'Grid',
  'Layers': 'Layers',
  'Palette': 'Palette',
  'ColorLens': 'Palette',
  'FormatPaint': 'PaintBucket',
  'Brush': 'Brush',
  'AttachMoney': 'DollarSign',
  'Money': 'DollarSign',
  'Euro': 'Euro',
  'Language': 'Globe',
  'Public': 'Globe',
  'Translate': 'Languages',
  'BugReport': 'Bug',
  'Extension': 'Puzzle',
  'Fingerprint': 'Fingerprint',
  'LightMode': 'Sun',
  'DarkMode': 'Moon',
  'Brightness4': 'Moon',
  'Brightness7': 'Sun',
};

// Component name mappings
export const componentNameMap: Record<string, string> = {
  'Button': 'Button',
  'TextField': 'Input',
  'Card': 'Card',
  'CardContent': 'CardContent',
  'CardActions': 'CardFooter',
  'Dialog': 'Modal',
  'DialogTitle': 'ModalHeader',
  'DialogContent': 'ModalBody',
  'DialogActions': 'ModalFooter',
  'Alert': 'Alert',
  'Tabs': 'TabNavigation',
  'Tab': 'TabItem',
  'Box': 'div', // Box is just a div in primitives
  'Container': 'div', // Container is just a div with max-width
  'Grid': 'div', // Grid should be replaced with CSS Grid/Flexbox
  'Typography': 'span', // Typography is handled via className
  'Paper': 'Card',
  'Divider': 'Separator',
  'List': 'ul',
  'ListItem': 'li',
  'ListItemText': 'span',
  'IconButton': 'Button',
  'Checkbox': 'Checkbox',
  'Radio': 'Radio',
  'RadioGroup': 'RadioGroup',
  'Select': 'Select',
  'MenuItem': 'option',
  'FormControl': 'FormItem',
  'FormLabel': 'FormLabel',
  'FormHelperText': 'FormDescription',
  'Switch': 'Switch',
  'Slider': 'Slider',
  'Tooltip': 'Tooltip',
  'Snackbar': 'Toast',
  'Avatar': 'Avatar',
  'Badge': 'Badge',
  'Chip': 'Badge',
  'CircularProgress': 'Loader',
  'LinearProgress': 'Progress',
  'Skeleton': 'Skeleton',
  'Accordion': 'Accordion',
  'AccordionSummary': 'AccordionTrigger',
  'AccordionDetails': 'AccordionContent',
  'AppBar': 'header',
  'Toolbar': 'nav',
  'Drawer': 'Sheet',
  'Menu': 'DropdownMenu',
  'Popover': 'Popover',
  'Modal': 'Modal',
  'Backdrop': 'Overlay',
  'Table': 'Table',
  'TableBody': 'TableBody',
  'TableCell': 'TableCell',
  'TableContainer': 'div',
  'TableHead': 'TableHeader',
  'TableRow': 'TableRow',
  'TablePagination': 'Pagination',
};

// Prop mappings
export const propMigrationMap: Record<string, Record<string, string>> = {
  'Button': {
    'variant="contained"': 'variant="default"',
    'variant="outlined"': 'variant="outline"',
    'variant="text"': 'variant="ghost"',
    'color="primary"': 'variant="default"',
    'color="secondary"': 'variant="secondary"',
    'color="error"': 'variant="destructive"',
    'color="warning"': 'variant="outline"',
    'color="info"': 'variant="default"',
    'color="success"': 'variant="default"',
    'size="small"': 'size="sm"',
    'size="medium"': 'size="default"',
    'size="large"': 'size="lg"',
    'startIcon': 'leftIcon',
    'endIcon': 'rightIcon',
    'fullWidth': 'className="w-full"',
    'disabled': 'disabled',
  },
  'TextField': {
    'variant="outlined"': 'variant="outlined"',
    'variant="filled"': 'variant="filled"',
    'variant="standard"': 'variant="underlined"',
    'size="small"': 'size="sm"',
    'size="medium"': 'size="md"',
    'label': '// Move label to separate FormLabel component',
    'helperText': '// Move helperText to separate FormDescription component',
    'error': 'state="error"',
    'fullWidth': 'className="w-full"',
    'multiline': '// Use Textarea component instead',
    'rows': 'rows',
    'disabled': 'disabled',
    'placeholder': 'placeholder',
    'type': 'type',
    'value': 'value',
    'onChange': 'onChange',
  },
  'IconButton': {
    'size="small"': 'size="icon" className="h-8 w-8"',
    'size="medium"': 'size="icon"',
    'size="large"': 'size="icon" className="h-12 w-12"',
    'color="primary"': 'variant="default"',
    'color="secondary"': 'variant="secondary"',
    'color="default"': 'variant="ghost"',
    'edge="start"': 'className="-ml-2"',
    'edge="end"': 'className="-mr-2"',
  }
};

export default {
  componentMigrationMap,
  iconMigrationMap,
  componentNameMap,
  propMigrationMap,
};