# Stub file for dotmac.platform.db module
from collections.abc import AsyncIterator, Iterator
from contextlib import AbstractContextManager
from typing import Any

from sqlalchemy.engine import Engine
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession
from sqlalchemy.orm import DeclarativeBase, Session

# Base classes
class Base(DeclarativeBase): ...

BaseModel = Base  # Legacy alias

# Mixins
class TimestampMixin:
    created_at: Any
    updated_at: Any

class TenantMixin:
    tenant_id: str

class SoftDeleteMixin:
    deleted_at: Any | None
    is_deleted: bool

class AuditMixin:
    created_by: str | None
    updated_by: str | None

# Session management
def get_db() -> Iterator[Session]: ...
def get_async_db() -> AsyncIterator[AsyncSession]: ...
def get_async_session() -> AsyncIterator[AsyncSession]: ...
def get_async_session_context() -> AsyncIterator[AsyncSession]: ...
def get_database_session() -> Iterator[Session]: ...
def get_db_session() -> Iterator[Session]: ...
def get_async_db_session() -> AsyncIterator[AsyncSession]: ...
def get_session() -> Iterator[Session]: ...
def get_session_dependency() -> AsyncIterator[AsyncSession]: ...

# Engines
def get_sync_engine() -> Engine: ...
def get_async_engine() -> AsyncEngine: ...

# Session factories
class SyncSessionLocal:
    def __call__(self) -> AbstractContextManager[Session]: ...

class AsyncSessionLocal:
    def __call__(self) -> AbstractContextManager[AsyncSession]: ...

async_session_maker: Any

# Database state
class DatabaseState: ...

def snapshot_database_state() -> DatabaseState: ...
def restore_database_state(state: DatabaseState) -> None: ...
def configure_database_for_testing() -> None: ...

# Database operations
def create_all_tables() -> None: ...
def create_all_tables_async() -> None: ...
def drop_all_tables() -> None: ...
def drop_all_tables_async() -> None: ...
def check_database_health() -> bool: ...
def init_db() -> None: ...

__all__: list[str]
