#!/bin/bash
# scripts/generate-db-config.sh
# Auto-detects server resources and generates optimal PostgreSQL configuration

set -e

echo "🔍 Detecting server resources..."
echo ""

# Detect system resources
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    TOTAL_RAM_MB=$(sysctl -n hw.memsize | awk '{print int($1/1024/1024)}')
    CPU_CORES=$(sysctl -n hw.ncpu)
else
    # Linux
    TOTAL_RAM_MB=$(free -m | awk '/^Mem:/{print $2}')
    CPU_CORES=$(nproc)
fi

echo "📊 Detected: ${TOTAL_RAM_MB}MB RAM, ${CPU_CORES} CPU cores"
echo ""

# Calculate optimal settings based on PostgreSQL best practices
# Reference: https://pgtune.leopard.in.ua/

# Shared buffers: 25% of RAM (but not more than 8GB for most workloads)
SHARED_BUFFERS=$((TOTAL_RAM_MB / 4))
if [ $SHARED_BUFFERS -gt 8192 ]; then
    SHARED_BUFFERS=8192
fi

# Effective cache size: 75% of RAM (hint to query planner)
EFFECTIVE_CACHE=$((TOTAL_RAM_MB * 3 / 4))

# Max connections: 50 connections per core, capped at 500
MAX_CONNECTIONS=$((CPU_CORES * 50))
if [ $MAX_CONNECTIONS -gt 500 ]; then
    MAX_CONNECTIONS=500
fi
if [ $MAX_CONNECTIONS -lt 100 ]; then
    MAX_CONNECTIONS=100
fi

# Work mem: (RAM / max_connections / 4) - memory for query operations
WORK_MEM=$((TOTAL_RAM_MB / MAX_CONNECTIONS / 4))
if [ $WORK_MEM -lt 4 ]; then
    WORK_MEM=4
fi

# Maintenance work mem: RAM / 16 (for VACUUM, CREATE INDEX, etc.)
MAINTENANCE_WORK_MEM=$((TOTAL_RAM_MB / 16))
if [ $MAINTENANCE_WORK_MEM -lt 64 ]; then
    MAINTENANCE_WORK_MEM=64
fi
if [ $MAINTENANCE_WORK_MEM -gt 2048 ]; then
    MAINTENANCE_WORK_MEM=2048
fi

# WAL buffers: shared_buffers / 32 (but max 16MB)
WAL_BUFFERS=$((SHARED_BUFFERS / 32))
if [ $WAL_BUFFERS -gt 16 ]; then
    WAL_BUFFERS=16
fi
if [ $WAL_BUFFERS -lt 1 ]; then
    WAL_BUFFERS=1
fi

# Effective I/O concurrency: 2x CPU cores for SSDs
EFFECTIVE_IO_CONCURRENCY=$((CPU_CORES * 2))

# Max worker processes: CPU cores
MAX_WORKER_PROCESSES=$CPU_CORES

# Max parallel workers per gather: CPU cores / 2
MAX_PARALLEL_WORKERS_PER_GATHER=$((CPU_CORES / 2))
if [ $MAX_PARALLEL_WORKERS_PER_GATHER -lt 2 ]; then
    MAX_PARALLEL_WORKERS_PER_GATHER=2
fi

# Max parallel workers: CPU cores
MAX_PARALLEL_WORKERS=$CPU_CORES

# Generate .env.db file
OUTPUT_FILE="${1:-.env.db}"

cat > "$OUTPUT_FILE" <<EOF
# PostgreSQL Configuration
# Auto-generated by generate-db-config.sh
# Server: ${TOTAL_RAM_MB}MB RAM, ${CPU_CORES} CPU cores
# Generated: $(date)
#
# These settings are optimized for a web application workload
# Adjust based on your specific needs

# Memory Configuration
# ---------------------
# Shared buffers: Amount of memory dedicated to PostgreSQL cache (25% of RAM)
DB_SHARED_BUFFERS=${SHARED_BUFFERS}MB

# Effective cache size: Hint to query planner about OS cache (75% of RAM)
DB_CACHE_SIZE=${EFFECTIVE_CACHE}MB

# Work mem: Memory for query operations like sorts and hash tables
DB_WORK_MEM=${WORK_MEM}MB

# Maintenance work mem: Memory for maintenance operations (VACUUM, CREATE INDEX)
DB_MAINTENANCE_WORK_MEM=${MAINTENANCE_WORK_MEM}MB

# Connection Configuration
# -------------------------
# Max connections: Maximum number of concurrent connections
DB_MAX_CONNECTIONS=${MAX_CONNECTIONS}

# WAL Configuration
# -----------------
# WAL buffers: Memory for write-ahead logging
DB_WAL_BUFFERS=${WAL_BUFFERS}MB

# Parallel Query Configuration
# -----------------------------
# Effective I/O concurrency: Expected concurrent I/O operations (SSDs)
DB_EFFECTIVE_IO_CONCURRENCY=${EFFECTIVE_IO_CONCURRENCY}

# Max worker processes: Background workers for maintenance and parallel queries
DB_MAX_WORKER_PROCESSES=${MAX_WORKER_PROCESSES}

# Max parallel workers per gather: Workers per parallel query node
DB_MAX_PARALLEL_WORKERS_PER_GATHER=${MAX_PARALLEL_WORKERS_PER_GATHER}

# Max parallel workers: Total parallel workers for all queries
DB_MAX_PARALLEL_WORKERS=${MAX_PARALLEL_WORKERS}

# Additional recommended settings
# --------------------------------
# Checkpoint completion target: Spread out checkpoint writes
DB_CHECKPOINT_COMPLETION_TARGET=0.9

# Random page cost: Lower for SSDs (default 4.0)
DB_RANDOM_PAGE_COST=1.1

# Min WAL size: Minimum WAL size
DB_MIN_WAL_SIZE=1GB

# Max WAL size: Maximum WAL size before checkpoint
DB_MAX_WAL_SIZE=4GB
EOF

echo "✅ PostgreSQL configuration written to: $OUTPUT_FILE"
echo ""
echo "📋 Configuration summary:"
echo "   Shared Buffers:       ${SHARED_BUFFERS}MB"
echo "   Effective Cache:      ${EFFECTIVE_CACHE}MB"
echo "   Max Connections:      ${MAX_CONNECTIONS}"
echo "   Work Mem:             ${WORK_MEM}MB"
echo "   Maintenance Work Mem: ${MAINTENANCE_WORK_MEM}MB"
echo ""
echo "💡 Usage:"
echo "   docker-compose --env-file .env --env-file $OUTPUT_FILE up postgres"
echo ""
echo "⚠️  Note: These are starting recommendations. Monitor performance and adjust as needed."
