global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
        labels:
          service: 'otel-collector'
  
  # Scrape application metrics if exposed
  - job_name: 'dotmac-services'
    static_configs:
      - targets: ['host.docker.internal:8000']
        labels:
          service: 'dotmac-api'