#!/bin/bash
# scripts/setup-config-files.sh
# Creates default configuration files for Docker Compose deployment

set -e

echo "🔧 Setting up default configuration files..."
echo ""

# Create directories
echo "📁 Creating directories..."
mkdir -p config/radius
mkdir -p config/awx
mkdir -p monitoring/prometheus
mkdir -p monitoring/grafana/dashboards
mkdir -p database/init

# Load environment variables if .env exists
if [ -f ".env" ]; then
    source .env
fi

# Create default RADIUS clients.conf if missing
if [ ! -f "config/radius/clients.conf" ]; then
    echo "📝 Creating config/radius/clients.conf..."
    cat > config/radius/clients.conf <<EOF
# FreeRADIUS Clients Configuration
# Auto-generated by setup-config-files.sh

client localhost {
    ipaddr = 127.0.0.1
    secret = ${RADIUS_SECRET:-changeme}
    require_message_authenticator = no
    nas_type = other
}

client docker_network {
    ipaddr = 172.16.0.0/12
    secret = ${RADIUS_SECRET:-changeme}
    require_message_authenticator = no
    nas_type = other
}

# Add your NAS devices here
# client nas1 {
#     ipaddr = 192.168.1.1
#     secret = ${RADIUS_SECRET:-changeme}
#     require_message_authenticator = no
#     nas_type = mikrotik
# }
EOF
fi

# Create default dictionary if missing
if [ ! -f "config/radius/dictionary" ]; then
    echo "📝 Creating config/radius/dictionary..."
    echo "# Downloading FreeRADIUS dictionary..."
    if command -v curl &> /dev/null; then
        curl -sL -o config/radius/dictionary https://raw.githubusercontent.com/FreeRADIUS/freeradius-server/v3.0.x/share/dictionary || {
            echo "⚠️  Failed to download dictionary, creating minimal version"
            cat > config/radius/dictionary <<EOF
# Minimal RADIUS dictionary
\$INCLUDE /usr/share/freeradius/dictionary

# Vendor-specific attributes can be added here
EOF
        }
    else
        echo "⚠️  curl not available, creating minimal dictionary"
        cat > config/radius/dictionary <<EOF
# Minimal RADIUS dictionary
\$INCLUDE /usr/share/freeradius/dictionary

# Vendor-specific attributes can be added here
EOF
    fi
fi

# Create default AWX settings if missing
if [ ! -f "config/awx/settings.py" ]; then
    echo "📝 Creating config/awx/settings.py..."
    if [ -f "config/awx/settings.py.example" ]; then
        cp config/awx/settings.py.example config/awx/settings.py
    else
        cat > config/awx/settings.py <<EOF
# AWX Settings
# Auto-generated by setup-config-files.sh

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'awx',
        'USER': 'awx',
        'PASSWORD': 'awx_password',
        'HOST': 'postgres',
        'PORT': '5432',
    }
}

BROKER_URL = 'redis://redis:6379/0'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('redis', 6379)],
        },
    },
}
EOF
    fi
fi

# Create default Prometheus config if missing
if [ ! -f "monitoring/prometheus/prometheus.yml" ]; then
    echo "📝 Creating monitoring/prometheus/prometheus.yml..."
    cat > monitoring/prometheus/prometheus.yml <<EOF
# Prometheus Configuration
# Auto-generated by setup-config-files.sh

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'dotmac-platform'
    environment: '${ENVIRONMENT:-production}'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Scrape configurations
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Add node-exporter if running on host
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['host.docker.internal:9100']
EOF
fi

# Create default Alertmanager config if missing
if [ ! -f "monitoring/prometheus/alertmanager.yml" ]; then
    echo "📝 Creating monitoring/prometheus/alertmanager.yml..."
    cat > monitoring/prometheus/alertmanager.yml <<EOF
# Alertmanager Configuration
# Auto-generated by setup-config-files.sh

global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://backend:8000/api/v1/monitoring/alerts/webhook'
        send_resolved: true

# Add additional receivers as needed
# - name: 'critical'
#   email_configs:
#     - to: 'ops@example.com'
#       from: 'alertmanager@example.com'
#       smarthost: 'smtp.example.com:587'
EOF
fi

# Create default Grafana dashboard provisioning config if missing
if [ ! -f "monitoring/grafana/dashboards/dashboard.yml" ]; then
    echo "📝 Creating monitoring/grafana/dashboards/dashboard.yml..."
    cat > monitoring/grafana/dashboards/dashboard.yml <<EOF
# Grafana Dashboard Provisioning
# Auto-generated by setup-config-files.sh

apiVersion: 1

providers:
  - name: 'Default'
    orgId: 1
    folder: ''
    type: file
    disableDeletion: false
    updateIntervalSeconds: 10
    allowUiUpdates: true
    options:
      path: /etc/grafana/provisioning/dashboards
EOF
fi

# Create .env if it doesn't exist
if [ ! -f ".env" ]; then
    echo "📝 Creating .env file with defaults..."
    cat > .env <<EOF
# Environment Configuration
# Auto-generated by setup-config-files.sh
# IMPORTANT: Update these values for production deployment

# Deployment
ENVIRONMENT=development
DEPLOYMENT_ENV=docker

# RADIUS
RADIUS_SECRET=changeme_radius_secret

# Database
POSTGRES_DB=dotmac
POSTGRES_USER=dotmac_user
POSTGRES_PASSWORD=changeme_db_password

# Redis
REDIS_PASSWORD=changeme_redis_password

# Application
SECRET_KEY=changeme_secret_key_at_least_32_characters
JWT_SECRET_KEY=changeme_jwt_secret_key_32_chars

# Monitoring (optional)
ENABLE_METRICS=true
ENABLE_TRACING=false
EOF
    echo "⚠️  IMPORTANT: Edit .env and update passwords before deployment!"
fi

echo ""
echo "✅ Configuration files created successfully"
echo ""
echo "📋 Next steps:"
echo "   1. Review and update .env file with production values"
echo "   2. Review generated config files and customize as needed"
echo "   3. Run: ./scripts/validate-docker-compose-env.sh"
echo "   4. Start services: docker-compose up -d"
