const now = new Date();
const isoNow = now.toISOString();

export const TEST_API_MOCKS: Record<string, unknown> = {
  "/api/v1/auth/me": {
    id: "test-user-id",
    email: "admin@test.local",
    fullName: "Test Admin",
    username: "admin",
    roles: ["admin"],
    permissions: ["*:*"],
    isPlatformAdmin: true,
    tenantId: "test-tenant-id",
    partnerId: "test-partner-id",
    activeOrganization: {
      id: "test-tenant-id",
      name: "Test Tenant",
      slug: "test-tenant",
      role: "admin",
      permissions: ["*"],
    },
  },
  "/api/v1/billing/metrics": {
    mrr: 1250000,
    arr: 15000000,
    outstanding: 450000,
    collectionRate: 94.5,
    overdueCount: 3,
    activeSubscriptions: 156,
    churnedThisMonth: 2,
    upgradesThisMonth: 8,
  },
  "/api/v1/billing/invoices": {
    invoices: [
      {
        id: "inv-001",
        number: "INV-2024-001",
        amount: 125000,
        status: "paid",
        currency: "USD",
        customer: {
          id: "cust-001",
          name: "Acme Corporation",
          email: "billing@acme.com",
        },
        lineItems: [
          {
            description: "Pro plan",
            quantity: 1,
            unitPrice: 125000,
            amount: 125000,
          },
        ],
        dueDate: isoNow,
        createdAt: isoNow,
      },
    ],
    totalCount: 1,
    page: 1,
    pageSize: 20,
    pageCount: 1,
  },
  "/api/v1/users": {
    items: [
      {
        id: "user-001",
        email: "admin@test.local",
        name: "Test Admin",
        role: "admin",
        status: "active",
        createdAt: isoNow,
        updatedAt: isoNow,
      },
      {
        id: "user-002",
        email: "user@test.local",
        name: "Test User",
        role: "member",
        status: "active",
        createdAt: isoNow,
        updatedAt: isoNow,
      },
    ],
    total: 2,
    page: 1,
    pageSize: 20,
    totalPages: 1,
  },
  "/api/v1/analytics/revenue": [
    { month: "Jan", revenue: 120000 },
    { month: "Feb", revenue: 135000 },
    { month: "Mar", revenue: 142000 },
    { month: "Apr", revenue: 151000 },
    { month: "May", revenue: 160000 },
    { month: "Jun", revenue: 172000 },
  ],
  "/api/v1/analytics/revenue/breakdown": {
    byPlan: [
      { plan: "Starter", revenue: 450000, percentage: 30 },
      { plan: "Professional", revenue: 750000, percentage: 50 },
      { plan: "Enterprise", revenue: 300000, percentage: 20 },
    ],
    byRegion: [
      { region: "North America", revenue: 900000, percentage: 60 },
      { region: "Europe", revenue: 450000, percentage: 30 },
      { region: "APAC", revenue: 150000, percentage: 10 },
    ],
    mrr: 1250000,
    arr: 15000000,
    mrrGrowth: 6.2,
    netRevenue: 1120000,
    churn: 1.8,
    expansion: 3.1,
  },
  "/api/v1/billing/payments": {
    payments: [
      {
        id: "pay-001",
        customerId: "cust-001",
        customerName: "Acme Corporation",
        invoiceId: "inv-001",
        invoiceNumber: "INV-2024-001",
        amount: 125000,
        currency: "USD",
        method: "card",
        status: "completed",
        paymentDate: isoNow,
        createdAt: isoNow,
      },
    ],
    total: 1,
    page: 1,
    pageSize: 20,
    pageCount: 1,
  },
  "/api/v1/deployments": {
    deployments: [
      {
        id: "deploy-001",
        name: "Production",
        state: "running",
        environment: "production",
        region: "us-east-1",
        version: "1.2.3",
        tenantId: "tenant-001",
        allocatedCpu: 2,
        allocatedMemoryGb: 8,
        allocatedStorageGb: 50,
        createdAt: isoNow,
        updatedAt: isoNow,
      },
    ],
  },
  "/api/v1/tenants": {
    tenants: [
      {
        id: "tenant-001",
        name: "Acme Corporation",
        domain: "acme.local",
        status: "active",
        plan: "professional",
        userCount: 15,
        createdAt: isoNow,
      },
    ],
    stats: {
      total: 1,
      active: 1,
      trial: 0,
      suspended: 0,
      totalChange: 5,
    },
  },
  "/api/v1/partners/portal/dashboard": {
    stats: {
      totalTenants: 4,
      activeTenants: 3,
      totalRevenueGenerated: 125000,
      totalCommissionsEarned: 18500,
      totalCommissionsPaid: 12000,
      pendingCommissions: 6500,
      totalReferrals: 24,
      convertedReferrals: 12,
      pendingReferrals: 8,
      conversionRate: 50,
      currentTier: "Gold",
      commissionModel: "Revenue share",
      defaultCommissionRate: 15,
    },
    revenueHistory: [
      { date: "Jan", revenue: 12000 },
      { date: "Feb", revenue: 13500 },
      { date: "Mar", revenue: 14200 },
      { date: "Apr", revenue: 15100 },
      { date: "May", revenue: 16000 },
      { date: "Jun", revenue: 17200 },
    ],
    commissionHistory: [
      { month: "Jan", amount: 1800 },
      { month: "Feb", amount: 2050 },
      { month: "Mar", amount: 2200 },
      { month: "Apr", amount: 2300 },
      { month: "May", amount: 2500 },
      { month: "Jun", amount: 2650 },
    ],
  },
  "/api/v1/partners/portal/referrals": {
    referrals: [
      {
        id: "ref-001",
        companyName: "Acme Corp",
        contactName: "Jane Doe",
        contactEmail: "jane@acme.com",
        status: "QUALIFIED",
        createdAt: isoNow,
        updatedAt: isoNow,
      },
    ],
    total: 1,
    page: 1,
    pageSize: 20,
  },
  "/api/v1/partners/portal/tenants": {
    tenants: [
      {
        id: "pt-001",
        tenantId: "tenant-001",
        tenantName: "Acme Corp",
        engagementType: "Referral",
        totalRevenue: 45000,
        totalCommissions: 6750,
        commissionRate: 15,
        startDate: isoNow,
        isActive: true,
      },
    ],
    total: 1,
    page: 1,
    pageSize: 20,
  },
  "/api/v1/partners/portal/commissions": {
    commissions: [
      {
        id: "com-001",
        tenantId: "tenant-001",
        tenantName: "Acme Corp",
        period: "2024-06",
        baseAmount: 12000,
        commissionRate: 15,
        commissionAmount: 1800,
        status: "PAID",
        paidAt: isoNow,
        createdAt: isoNow,
      },
    ],
    total: 1,
    page: 1,
    pageSize: 20,
    summary: {
      totalPending: 0,
      totalApproved: 0,
      totalPaid: 1800,
    },
  },
  "/api/v1/partners/portal/statements": {
    statements: [
      {
        id: "stmt-001",
        period: "2024-06",
        startDate: isoNow,
        endDate: isoNow,
        totalRevenue: 12000,
        totalCommissions: 1800,
        status: "PAID",
        paidAt: isoNow,
        createdAt: isoNow,
      },
    ],
    total: 1,
    page: 1,
    pageSize: 20,
  },
  "/api/v1/partners/portal/profile": {
    id: "partner-001",
    companyName: "Partner Solutions",
    contactName: "Jane Doe",
    contactEmail: "jane@partner.com",
    commissionRate: 15,
    tier: "GOLD",
    joinedAt: isoNow,
    payoutPreferences: { method: "BANK_TRANSFER" },
    notificationSettings: {
      emailNewReferral: true,
      emailCommissionApproved: true,
      emailPayoutProcessed: true,
      emailMonthlyStatement: true,
    },
  },
  "/api/v1/partners/portal/users": {
    users: [
      {
        id: "partner-user-1",
        partnerId: "partner-001",
        userId: "user-1",
        firstName: "Partner",
        lastName: "Admin",
        fullName: "Partner Admin",
        email: "partner@dotmac.com",
        role: "partner_admin",
        isPrimaryContact: true,
        isActive: true,
        createdAt: isoNow,
        updatedAt: isoNow,
      },
    ],
  },
  "/api/v1/partners/portal/invitations": {
    invitations: [
      {
        id: "partner-invite-1",
        partnerId: "partner-001",
        email: "invitee@partner.com",
        role: "partner_admin",
        status: "pending",
        invitedBy: "Partner Admin",
        createdAt: isoNow,
        expiresAt: isoNow,
      },
    ],
  },
  "/api/v1/tenants/portal/dashboard": {
    stats: {
      activeUsers: 12,
      maxUsers: 25,
      apiCallsThisMonth: 45000,
      apiCallsLimit: 100000,
      storageUsedMb: 1200,
      storageLimitMb: 5000,
      daysUntilRenewal: 18,
      planName: "Professional",
      planType: "PROFESSIONAL",
    },
    recentActivity: [
      {
        id: "act-1",
        type: "user_joined",
        description: "Alex Johnson joined your workspace",
        createdAt: isoNow,
      },
    ],
  },
  "/api/v1/tenants/portal/billing": {
    subscription: {
      id: "sub-001",
      planName: "Professional",
      planType: "PROFESSIONAL",
      status: "ACTIVE",
      currentPeriodStart: isoNow,
      currentPeriodEnd: isoNow,
      cancelAtPeriodEnd: false,
      monthlyPrice: 9900,
      billingInterval: "monthly",
    },
    invoices: [
      {
        id: "tp-inv-1",
        number: "INV-2024-001",
        status: "PAID",
        amountDue: 0,
        amountPaid: 9900,
        currency: "USD",
        periodStart: isoNow,
        periodEnd: isoNow,
        paidAt: isoNow,
        createdAt: isoNow,
      },
    ],
    paymentMethods: [],
  },
  "/api/v1/tenants/portal/invoices": {
    invoices: [
      {
        id: "tp-inv-1",
        number: "INV-2024-001",
        status: "PAID",
        amountDue: 0,
        amountPaid: 9900,
        currency: "USD",
        periodStart: isoNow,
        periodEnd: isoNow,
        paidAt: isoNow,
        createdAt: isoNow,
      },
    ],
    total: 1,
    page: 1,
    pageSize: 20,
  },
  "/api/v1/tenants/portal/usage": {
    apiCalls: {
      current: 45000,
      limit: 100000,
      unit: "calls",
      percentUsed: 45,
      history: [{ date: "2024-06-01", value: 1500 }],
    },
    storage: {
      current: 1200,
      limit: 5000,
      unit: "MB",
      percentUsed: 24,
      history: [{ date: "2024-06-01", value: 300 }],
    },
    users: {
      current: 12,
      limit: 25,
      unit: "users",
      percentUsed: 48,
      history: [{ date: "2024-06-01", value: 10 }],
    },
    bandwidth: {
      current: 320,
      limit: 1000,
      unit: "GB",
      percentUsed: 32,
      history: [{ date: "2024-06-01", value: 50 }],
    },
  },
  "/api/v1/tenants/portal/usage/breakdown": {
    byFeature: [
      { feature: "API", calls: 30000, percentage: 66 },
      { feature: "Webhooks", calls: 15000, percentage: 34 },
    ],
    byUser: [
      { userId: "user-1", userName: "Alex Johnson", apiCalls: 12000, storageUsed: 200 },
    ],
  },
  "/api/v1/tenants/portal/settings": {
    general: {
      name: "Acme Corp",
      slug: "acme",
      timezone: "UTC",
      dateFormat: "YYYY-MM-DD",
      language: "en",
    },
    branding: {},
    security: {
      mfaRequired: false,
      sessionTimeout: 30,
      ipWhitelist: [],
      allowedDomains: [],
    },
    features: {
      advancedAnalytics: false,
      customIntegrations: false,
      apiAccess: true,
    },
  },
  "/api/v1/tenants/portal/members": {
    members: [
      {
        id: "member-1",
        userId: "user-1",
        email: "alex@acme.com",
        fullName: "Alex Johnson",
        role: "tenant_admin",
        status: "ACTIVE",
        joinedAt: isoNow,
      },
    ],
    total: 1,
    page: 1,
    pageSize: 20,
  },
  "/api/v1/tenants/portal/invitations": {
    invitations: [
      {
        id: "invite-1",
        email: "invitee@acme.com",
        role: "member",
        status: "PENDING",
        invitedBy: "Alex Johnson",
        invitedByName: "Alex Johnson",
        createdAt: isoNow,
        expiresAt: isoNow,
      },
    ],
    total: 1,
  },
  "/api/v1/tenants/portal/api-keys": [
    {
      id: "key-1",
      name: "Primary API Key",
      prefix: "dmk",
      createdAt: isoNow,
      createdBy: "Alex Johnson",
    },
  ],
};

export function getTestMockResponse(endpoint: string): unknown | undefined {
  if (TEST_API_MOCKS[endpoint]) {
    return TEST_API_MOCKS[endpoint];
  }
  return undefined;
}
