"use client";

import { Partner } from "@/hooks/usePartners";

interface PartnerMetricsProps {
  partners: Partner[];
}

export default function PartnerMetrics({ partners }: PartnerMetricsProps) {
  const stats = {
    total: partners.length,
    active: partners.filter((p) => p.status === "active").length,
    totalRevenue: partners.reduce((sum, p) => sum + p.total_revenue_generated, 0),
    pendingCommissions: partners.reduce(
      (sum, p) => sum + (p.total_commissions_earned - p.total_commissions_paid),
      0
    ),
    totalReferrals: partners.reduce((sum, p) => sum + p.total_referrals, 0),
    convertedReferrals: partners.reduce((sum, p) => sum + p.converted_referrals, 0),
  };

  const conversionRate =
    stats.totalReferrals > 0
      ? ((stats.convertedReferrals / stats.totalReferrals) * 100).toFixed(1)
      : "0.0";

  return (
    <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4 mb-6">
      <div className="bg-slate-800 p-6 rounded-lg border border-slate-700">
        <div className="text-sm text-slate-400 mb-1">Total Partners</div>
        <div className="text-3xl font-bold text-white">{stats.total}</div>
        <div className="text-xs text-slate-500 mt-1">
          {stats.active} active
        </div>
      </div>

      <div className="bg-slate-800 p-6 rounded-lg border border-slate-700">
        <div className="text-sm text-slate-400 mb-1">Total Revenue</div>
        <div className="text-3xl font-bold text-white">
          ${stats.totalRevenue.toLocaleString()}
        </div>
        <div className="text-xs text-slate-500 mt-1">
          Generated by partners
        </div>
      </div>

      <div className="bg-slate-800 p-6 rounded-lg border border-slate-700">
        <div className="text-sm text-slate-400 mb-1">Pending Commissions</div>
        <div className="text-3xl font-bold text-yellow-400">
          ${stats.pendingCommissions.toLocaleString()}
        </div>
        <div className="text-xs text-slate-500 mt-1">
          Awaiting payout
        </div>
      </div>

      <div className="bg-slate-800 p-6 rounded-lg border border-slate-700">
        <div className="text-sm text-slate-400 mb-1">Referral Conversion</div>
        <div className="text-3xl font-bold text-green-400">{conversionRate}%</div>
        <div className="text-xs text-slate-500 mt-1">
          {stats.convertedReferrals} of {stats.totalReferrals} converted
        </div>
      </div>
    </div>
  );
}
